version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing AWS SAM CLI...
      - wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
      - sudo ./sam-installation/install

  pre_build:
    commands:
      - echo Installing function dependencies...
      - |
        for dir in lambda-functions/*; do
          if [ -f "$dir/package.json" ]; then
            echo "Installing in $dir"
            (cd "$dir" && npm install)
          fi
        done

  build:
    commands:
      - echo Building with SAM....
      - sam build

  post_build:
    commands:
      - echo Deploying with SAM...
      - sam deploy --template-file .aws-sam/build/template.yaml --stack-name my-lambda-stack --capabilities CAPABILITY_IAM --region us-east-1 --resolve-s3

artifacts:
  files:
    - template.yaml
